name: Build Module Pro

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Forked Code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref_name }}

    - name: Install Essential Build Tools
      run: |
        sudo apt-get update
        sudo apt-get install -y bc bison flex libelf-dev libssl-dev rsync

    - name: Prepare Kernel Configuration
      run: |
        cd ${{ github.workspace }}
        
        # Architecture set karenge
        export ARCH=arm64
        export SUBARCH=arm64
        
        # GitHub ka built-in Clang aur LLD use karne ke liye LLVM=1 force karenge
        make LLVM=1 CC=clang LD=ld.lld olddefconfig

    - name: Build Module (.ko)
      run: |
        cd ${{ github.workspace }}/filetest
        
        export ARCH=arm64
        export SUBARCH=arm64
        
        # GitHub ke default compiler se direct compilation
        make LLVM=1 CC=clang LD=ld.lld KDIR=${{ github.workspace }}

    - name: Upload Finished Module
      uses: actions/upload-artifact@v4
      with:
        name: OnePlus-13R-Module
        path: filetest/*.ko
